In [1]:
import pandas as pd

test_df=pd.read_csv("test_dataset.csv") 
test_df.head()

,Id,OrgId,IncidentId,AlertId,Timestamp,DetectorId,AlertTitle,Category,MitreTechniques,IncidentGrade,...,Roles,OSFamily,OSVersion,AntispamDirection,SuspicionLevel,LastVerdict,CountryCode,State,City,Usage
0,996432416945,573,37794,1042788,2024-06-06T02:36:32.000Z,0,0,InitialAccess,T1078;T1078.004,FalsePositive,...,NaN,5,66,NaN,NaN,NaN,0,1,1349,Public
1,841813591828,0,91,389681,2024-06-07T16:35:53.000Z,4,3,InitialAccess,NaN,TruePositive,...,NaN,5,66,NaN,NaN,NaN,5,1445,10630,Public
2,1382979472797,302,1101,249487,2024-06-07T11:18:10.000Z,2,2,CommandAndControl,NaN,BenignPositive,...,NaN,5,66,NaN,Suspicious,Suspicious,242,1445,10630,Public
3,103079215716,558,116109,117294,2024-06-03T20:04:28.000Z,6,5,InitialAccess,T1566,TruePositive,...,NaN,5,66,NaN,NaN,NaN,242,1445,10630,Private
4,1494648622924,752,30572,63284,2024-06-03T11:56:04.000Z,1,1,InitialAccess,T1566.002,TruePositive,...,NaN,5,66,Inbound,NaN,NoThreatsFound,242,1445,10630,Public

In [13]:
test_df.drop(columns=["ActionGrouped","ActionGranular","EmailClusterId","ThreatFamily","ResourceType","Roles","AntispamDirection"],inplace=True)

In [15]:
test_df.drop(columns=["SuspicionLevel","LastVerdict"], inplace=True)

In [16]:
test_df.drop(columns=["OrgId","EvidenceRole","Sha256","AccountUpn","AccountObjectId","RegistryValueName","RegistryValueData"],inplace=True)

In [19]:
test_df.drop(columns=["OAuthApplicationId","ResourceIdName","State","City"],inplace=True)

In [21]:
test_df.drop(columns=["AlertTitle","OSVersion"],inplace=True)

In [23]:
test_df.drop(columns=["Id","IncidentId","AlertId","DetectorId","NetworkMessageId"],inplace=True)

In [25]:
test_df.drop(columns=["ApplicationName","ApplicationId","RegistryKey","OSFamily"],inplace=True)

In [29]:
test_df.drop(columns=["MitreTechniques"],inplace=True)

In [31]:
test_df.head()

,Timestamp,Category,IncidentGrade,EntityType,DeviceId,IpAddress,Url,AccountSid,AccountName,DeviceName,FileName,FolderPath,CountryCode,Usage
0,2024-06-06T02:36:32.000Z,InitialAccess,FalsePositive,Ip,98799,134840,160396,441377,453297,153085,289573,117668,0,Public
1,2024-06-07T16:35:53.000Z,InitialAccess,TruePositive,Ip,98799,11856,160396,441377,453297,153085,289573,117668,5,Public
2,2024-06-07T11:18:10.000Z,CommandAndControl,BenignPositive,Process,98799,360606,160396,441377,453297,153085,151,148,242,Public
3,2024-06-03T20:04:28.000Z,InitialAccess,TruePositive,User,98799,360606,160396,95162,103526,153085,289573,117668,242,Private
4,2024-06-03T11:56:04.000Z,InitialAccess,TruePositive,MailMessage,98799,360606,160396,441377,453297,153085,289573,117668,242,Public

In [35]:
test_df["Timestamp"]=pd.to_datetime(test_df["Timestamp"])

In [37]:
test_df['hour'] = test_df['Timestamp'].dt.hour
test_df['day'] = test_df['Timestamp'].dt.day
test_df['month'] = test_df['Timestamp'].dt.month
test_df['weekday'] = test_df['Timestamp'].dt.weekday

In [46]:
test_df.drop(columns=['Usage'],inplace=True)

In [58]:
import pandas as pd 

cols=[col for col in test_df.columns if col!="IncidentGrade"]
cols.append("IncidentGrade") 

test_df=test_df[cols] 
test_df.head()

,Category,EntityType,DeviceId,IpAddress,Url,AccountSid,AccountName,DeviceName,FileName,FolderPath,CountryCode,hour,day,month,weekday,IncidentGrade
0,InitialAccess,Ip,98799,134840,160396,441377,453297,153085,289573,117668,0,2,6,6,3,FalsePositive
1,InitialAccess,Ip,98799,11856,160396,441377,453297,153085,289573,117668,5,16,7,6,4,TruePositive
2,CommandAndControl,Process,98799,360606,160396,441377,453297,153085,151,148,242,11,7,6,4,BenignPositive
3,InitialAccess,User,98799,360606,160396,95162,103526,153085,289573,117668,242,20,3,6,0,TruePositive
4,InitialAccess,MailMessage,98799,360606,160396,441377,453297,153085,289573,117668,242,11,3,6,0,TruePositive

In [60]:
from sklearn.preprocessing import LabelEncoder 

le=LabelEncoder() 

test_df["IncidentGrade"]=le.fit_transform(test_df["IncidentGrade"])
test_df.head()

,Category,EntityType,DeviceId,IpAddress,Url,AccountSid,AccountName,DeviceName,FileName,FolderPath,CountryCode,hour,day,month,weekday,IncidentGrade
0,InitialAccess,Ip,98799,134840,160396,441377,453297,153085,289573,117668,0,2,6,6,3,1
1,InitialAccess,Ip,98799,11856,160396,441377,453297,153085,289573,117668,5,16,7,6,4,2
2,CommandAndControl,Process,98799,360606,160396,441377,453297,153085,151,148,242,11,7,6,4,0
3,InitialAccess,User,98799,360606,160396,95162,103526,153085,289573,117668,242,20,3,6,0,2
4,InitialAccess,MailMessage,98799,360606,160396,441377,453297,153085,289573,117668,242,11,3,6,0,2

In [66]:
                                           #TARGET ENCODING FOR CATEGORICAL COLUMNS

import pandas as pd


columns_to_encode = ['Category','EntityType','DeviceId', 'IpAddress', 'Url', 'AccountSid', 'AccountName', 'DeviceName', 'FileName', 'FolderPath', 'CountryCode']


for column in columns_to_encode:
    column_mean = test_df.groupby(column)['IncidentGrade'].mean()
    
    
    test_df[column] = test_df[column].map(column_mean).round(3)


test_df.head()

,Category,EntityType,DeviceId,IpAddress,Url,AccountSid,AccountName,DeviceName,FileName,FolderPath,CountryCode,hour,day,month,weekday,IncidentGrade
0,1.304,1.205,1.012,1.000,1.019,0.967,0.975,1.029,1.048,1.044,1.607,2,6,6,3,1
1,1.304,1.205,1.012,2.000,1.019,0.967,0.975,1.029,1.048,1.044,1.986,16,7,6,4,2
2,0.586,0.597,1.012,0.939,1.019,0.967,0.975,1.029,0.298,0.298,0.929,11,7,6,4,0
3,1.304,1.116,1.012,0.939,1.019,2.000,2.000,1.029,1.048,1.044,0.929,20,3,6,0,2
4,1.304,0.636,1.012,0.939,1.019,0.967,0.975,1.029,1.048,1.044,0.929,11,3,6,0,2

In [68]:
import pandas as pd 


columns_to_encode= ['hour', 'day', 'month', 'weekday'] 

for column in columns_to_encode:
     column_mean = test_df.groupby(column)['IncidentGrade'].mean()
     
     
     test_df[column]=test_df[column].map(column_mean).round(3) 


test_df.head()

,Category,EntityType,DeviceId,IpAddress,Url,AccountSid,AccountName,DeviceName,FileName,FolderPath,CountryCode,hour,day,month,weekday,IncidentGrade
0,1.304,1.205,1.012,1.000,1.019,0.967,0.975,1.029,1.048,1.044,1.607,1.090,1.067,1.005,1.005,1
1,1.304,1.205,1.012,2.000,1.019,0.967,0.975,1.029,1.048,1.044,1.986,0.944,1.107,1.005,0.966,2
2,0.586,0.597,1.012,0.939,1.019,0.967,0.975,1.029,0.298,0.298,0.929,0.983,1.107,1.005,0.966,0
3,1.304,1.116,1.012,0.939,1.019,2.000,2.000,1.029,1.048,1.044,0.929,0.940,1.037,1.005,0.980,2
4,1.304,0.636,1.012,0.939,1.019,0.967,0.975,1.029,1.048,1.044,0.929,0.983,1.037,1.005,0.980,2

In [72]:
test_df.to_csv("test_df.csv",index=False)

In [74]:
import pandas as pd 

final_test_df=pd.read_csv("test_df.csv") 
final_test_df.head()

,Category,EntityType,DeviceId,IpAddress,Url,AccountSid,AccountName,DeviceName,FileName,FolderPath,CountryCode,hour,day,month,weekday,IncidentGrade
0,1.304,1.205,1.012,1.000,1.019,0.967,0.975,1.029,1.048,1.044,1.607,1.090,1.067,1.005,1.005,1
1,1.304,1.205,1.012,2.000,1.019,0.967,0.975,1.029,1.048,1.044,1.986,0.944,1.107,1.005,0.966,2
2,0.586,0.597,1.012,0.939,1.019,0.967,0.975,1.029,0.298,0.298,0.929,0.983,1.107,1.005,0.966,0
3,1.304,1.116,1.012,0.939,1.019,2.000,2.000,1.029,1.048,1.044,0.929,0.940,1.037,1.005,0.980,2
4,1.304,0.636,1.012,0.939,1.019,0.967,0.975,1.029,1.048,1.044,0.929,0.983,1.037,1.005,0.980,2

In [76]:
                             #MODEL LOAD FROM TRAIN DATASET

import joblib

Best_train_model=joblib.load("best_model_rf.pkl") 
print(Best_train_model)

RandomForestClassifier(random_state=42)

In [80]:
X=final_test_df.drop(columns=["IncidentGrade"]) 
y=final_test_df["IncidentGrade"] 


y_pred_t=Best_train_model.predict(X) 
y_pred_t

array([1, 2, 0, ..., 2, 1, 2], dtype=int64)

In [82]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

accuracy = accuracy_score(y, y_pred_t)
print("Accuracy score:", accuracy)


print("Classification report:")
print(classification_report(y, y_pred_t))


print("Confusion matrix:")
print(confusion_matrix(y, y_pred_t))

Accuracy score: 0.7938286666666666
Classification report:
              precision    recall  f1-score   support

           0       0.79      0.82      0.80    500000
           1       0.80      0.68      0.74    500000
           2       0.79      0.88      0.83    500000

    accuracy                           0.79   1500000
   macro avg       0.79      0.79      0.79   1500000
weighted avg       0.79      0.79      0.79   1500000

Confusion matrix:
[[409347  59163  31490]
 [ 72958 342012  85030]
 [ 34717  25899 439384]]

In [ ]:
i have selected Random forest as best model in Training dataset, and then i test that on unseen test dataset.
Random Forest model is performing decently well on the unseen test dataset with an accuracy of 79%. 
The accuracy of the model is 0.79 (79%). This means the model correctly predicted the labels for 79% of the total data in the test set 
The model's strength lies in its ability to identify class 2 correctly (high recall), wheres class 0 and class 1 also performs good...